$schema: ./schema.json
# Native
App:
  Landscape: pichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Pichu Alcohol Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Database:
  MAIN:
    AutoMigrate: false

Cache:
  MAIN:
    SSL: true

# external
HttpClient:
  Logto:
    BaseAddress: https://admin.lithium.alcohol.pichu.atomi.cloud
Auth:
  Enabled: true
  Settings:
    Issuer: https://admin.lithium.alcohol.pichu.atomi.cloud/oidc
    Audience: https://api.zinc.alcohol.pichu
    Domain: admin.lithium.alcohol.pichu.atomi.cloud/oidc
  Management:
    Endpoint: https://admin.lithium.alcohol.pichu.atomi.cloud
    Id: q821ucbj78gyppgqsx179
    Secret: supersecret
    Resource: https://default.logto.app/api
    Scope: all
