$schema: ./schema.json
# Native
App:
  Landscape: raichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Raichu Alcohol Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Database:
  MAIN:
    AutoMigrate: false

Cache:
  MAIN:
    SSL: true
# external
HttpClient:
  Logto:
    BaseAddress: https://admin.lithium.alcohol.raichu.atomi.cloud
Auth:
  Enabled: true
  Settings:
    Issuer: https://admin.lithium.alcohol.raichu.atomi.cloud/oidc
    Audience: https://api.zinc.alcohol.raichu
    Domain: admin.lithium.alcohol.raichu.atomi.cloud/oidc
  Management:
    Endpoint: https://admin.lithium.alcohol.raichu.atomi.cloud
    Id: xtd72hm10b85nib956r85
    Secret: supersecret
    Resource: https://default.logto.app/api
    Scope: all
